# CrumbPanel - Minecraft Server Management Panel
# Made by paulify.dev (https://paulify.eu)
# Repository: https://github.com/panie18/crumbpanel

version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: mc_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mc_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mc_password}
      POSTGRES_DB: ${POSTGRES_DB:-mc_panel}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mc_admin}"]
      interval: 3s
      timeout: 3s
      retries: 20
    networks:
      - crumbpanel

  backend:
    build: ./backend
    container_name: mc_backend
    env_file: .env
    ports:
      - "0.0.0.0:5829:5829"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data/backups:/app/backups
      - ./data/servers:/app/servers
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5829
      - DATABASE_URL=postgresql://${POSTGRES_USER:-mc_admin}:${POSTGRES_PASSWORD:-mc_password}@db:5432/${POSTGRES_DB:-mc_panel}
    networks:
      - crumbpanel

  frontend:
    build: ./frontend
    container_name: mc_frontend
    ports:
      - "0.0.0.0:8437:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - crumbpanel

volumes:
  db_data:

networks:
  crumbpanel:
    driver: bridge
